export const RYDA_CONFIG = Object.freeze({
  KEKE_SEAT_CAPACITY: 4,
  RIDE_FARE_PER_SEAT_NGN: 150,
  COURIER_FARE_NGN: 150,
  PLATFORM_FEE_RATE: 0.1,
  PAYMENT_GRACE_PERIOD_MINUTES: 60
});

export const SERVICE_STATUSES = Object.freeze({
  DRIVER_VERIFICATION: ['PENDING', 'APPROVED', 'REJECTED'],
  RIDE: ['REQUESTED', 'ACCEPTED', 'DRIVER_ARRIVING', 'DRIVER_ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW'],
  COURIER: ['REQUESTED', 'ACCEPTED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED'],
  PAYMENT: ['PENDING', 'PAID', 'FAILED', 'REFUNDED'],
  LIABILITY: ['PENDING', 'SETTLED', 'OVERDUE', 'WAIVED'],
  WITHDRAWAL: ['PENDING', 'APPROVED', 'REJECTED', 'PAID']
});
